### ISSUE TITLE
Practica2 Interfaz Grafica

### ISSUE THREAD

**Issue by Julissamigdalia** [SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-topicos-avanzados-4us#2]
[interfaz practica2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-topicos-avanzados-4us/files/10772452/interfaz.practica2.pdf)

**Comment by ToniDepp** [comment]
**Portada:** 20% Aunque carece de formato es una portada que cumple con lo que se pide.
**Procedimiento:** 20% Aunque algunas herramientas fueron mencionadas en el procedimiento, se saltaron procesos y solo mostraron el resultado final.
**Figuras ilustraciones y fotografías:** 20% Carecen de formato y no se aprovechan los espacios en blanco que dejaron.
**Resultados y conclusiones:** 17% No dejan tan claro que aprendieron y como fue su interacción como equipo.

Calificación: 77%/100% = 15.4/20

Calificado por el Equipo 2

**Comment by josealfredo79** [comment]
Bien hecho y revisado
